### ISSUE TITLE
Add highlights stories support

### ISSUE THREAD

**Issue by fzn0x** [2pai/instastory-monitor-telegram#13]
Get highlights stories by collector

**Comment by 2pai** [comment]
Do we actually need this feature? I don't think so, because the purpose of the project was to get notified when the target user create a new Instagram story. 
so it's doesn't matter if the story itself gets highlighted or not.

**Comment by fzn0x** [comment]
> Do we actually need this feature? I don't think so, because the purpose of the project was to get notified when the target user create a new Instagram story.
> so it's doesn't matter if the story itself gets highlighted or not.

Ok, thank you!
