### ISSUE TITLE
npm run collect throwing IgSentryBlockError: POST /api/v1/accounts/login/ - 400 Bad Request

### ISSUE THREAD

**Issue by mupinnn** [2pai/instastory-monitor-telegram#19]
Hi! I'm trying to run `npm run collect` but it doesn't seem to run well. I've filled `.env` with my IG username and password, also the target username. I leave the telegram and discord `.env` blank because I just want to test the stories collecting and download.

I have no idea about the code inside `collector.js`, I guess that's fine. Or maybe my environment doesn't meet the requirement of  `instagram-private-api` package?

I'm testing this with my instagram ONLY active & logged in on instagram web. I'm not sure if that package requires having instagram account active on the phone.

## Expected Behavior
Stories data collected and saved to `metadata-story.json` and `storyUID.json`

## Actual Behavior
![image](https://user-images.githubusercontent.com/46535277/111909951-db5b0b00-8a91-11eb-8dc2-265d48a8c51a.png)

## Environment
- Node : v12.21.0
- OS : Ubuntu 20.04.2 LTS x86_64

Thanks you!!

**Comment by 2pai** [comment]
This might be an issue with your account / IP address, is your account has 2FA enabled? have you try with a different account?

**Comment by mupinnn** [comment]
My 2FA not enabled, and yes this is an issue with my IP address. I refer to these issues dilame/instagram-private-api#795, dilame/instagram-private-api#345, my IP got blocked for a while, perhaps.

I'm trying it again this morning, and it's work.

Thankss!
